#!/bin/bash

echo "#include <stdlib.h>
#include <stdio.h>
#include <time.h> 
#include <unistd.h>

int 
main(int argv, char *argc[]) {


}" > $1.c

echo "CC = gcc
CFLAGS = -Wall -std-c99 -o $1 $2

all:    
        \$(CC) \$(CFLAGS) $1.c" > Makefile

vim -p $1.c Makefile
